name: build

on:
  push:
    branches: add-arm-build
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup go environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.16.5'
      - name: Build CLI
        run: make build-linux
      - name: Check version
        run: bin/linux/amd64/oras version
