name: build

on:
  push:
    branches: add-arm-build
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: setup go environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.16.5'
      - name: Build CLI
        run: make build-linux-arm32
      - name: Check version
        run: bin/linux/arm32/oras version
